//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Utility {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ResourcePersonel {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ResourcePersonel() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Utility.ResourcePersonel", typeof(ResourcePersonel).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @adParam.
        /// </summary>
        public static string AdParam {
            get {
                return ResourceManager.GetString("AdParam", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Departman Seçiniz...
        /// </summary>
        public static string cmbDepartmanDefaultValue {
            get {
                return ResourceManager.GetString("cmbDepartmanDefaultValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DELETE FROM TblSatis WHERE PERSONEL=@p1; DELETE FROM TblPersonel WHERE PERID=@p1.
        /// </summary>
        public static string DeletePersonelSorgu {
            get {
                return ResourceManager.GetString("DeletePersonelSorgu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DEPARTMANAD.
        /// </summary>
        public static string DEPARTMANAD {
            get {
                return ResourceManager.GetString("DEPARTMANAD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @departmanParam.
        /// </summary>
        public static string DepartmanParam {
            get {
                return ResourceManager.GetString("DepartmanParam", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @p1.
        /// </summary>
        public static string IdParameter {
            get {
                return ResourceManager.GetString("IdParameter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to INSERT INTO TblPersonel(PERAD, PERSOYAD, PERDEPARTMAN, PERMAAS) VALUES (@p1, @p2, @p3, @p4).
        /// </summary>
        public static string InsertPersonelSorgu {
            get {
                return ResourceManager.GetString("InsertPersonelSorgu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @maasParam.
        /// </summary>
        public static string MaasParam {
            get {
                return ResourceManager.GetString("MaasParam", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @p1.
        /// </summary>
        public static string Parameter1 {
            get {
                return ResourceManager.GetString("Parameter1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @p2.
        /// </summary>
        public static string Parameter2 {
            get {
                return ResourceManager.GetString("Parameter2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @p3.
        /// </summary>
        public static string Parameter3 {
            get {
                return ResourceManager.GetString("Parameter3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @p4.
        /// </summary>
        public static string Parameter4 {
            get {
                return ResourceManager.GetString("Parameter4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PERAD.
        /// </summary>
        public static string PERSONELAD {
            get {
                return ResourceManager.GetString("PERSONELAD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PERDEPARTMAN.
        /// </summary>
        public static string PERSONELDEPARTMAN {
            get {
                return ResourceManager.GetString("PERSONELDEPARTMAN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Personel eklenemedi! Lütfen tüm bilgileri eksiksiz giriniz..
        /// </summary>
        public static string PersonelEkleError {
            get {
                return ResourceManager.GetString("PersonelEkleError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Personel güncellenemedi! Lütfen tüm bilgileri eksiksiz giriniz..
        /// </summary>
        public static string PersonelGuncelleError {
            get {
                return ResourceManager.GetString("PersonelGuncelleError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PERID.
        /// </summary>
        public static string PERSONELID {
            get {
                return ResourceManager.GetString("PERSONELID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Personeller.aspx.
        /// </summary>
        public static string PersonellerSayfasi {
            get {
                return ResourceManager.GetString("PersonellerSayfasi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PERMAAS.
        /// </summary>
        public static string PERSONELMAAS {
            get {
                return ResourceManager.GetString("PERSONELMAAS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PERSOYAD.
        /// </summary>
        public static string PERSONELSOYAD {
            get {
                return ResourceManager.GetString("PERSONELSOYAD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT * FROM TblPersonel WHERE PERID=@p1.
        /// </summary>
        public static string SelectPersonelByIdSorgu {
            get {
                return ResourceManager.GetString("SelectPersonelByIdSorgu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT * FROM TblPersonel.
        /// </summary>
        public static string SelectPersonelSorgu {
            get {
                return ResourceManager.GetString("SelectPersonelSorgu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @soyadParam.
        /// </summary>
        public static string SoyadParam {
            get {
                return ResourceManager.GetString("SoyadParam", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DEPARTMANLIST.
        /// </summary>
        public static string spSelectPersonelwithDepartmanAd {
            get {
                return ResourceManager.GetString("spSelectPersonelwithDepartmanAd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UPDATE TblPersonel SET PERAD=@adParam, PERSOYAD=@soyadParam, PERDEPARTMAN=@departmanParam, PERMAAS=@maasParam WHERE PERID=@p1.
        /// </summary>
        public static string UpdatePersonelSorgu {
            get {
                return ResourceManager.GetString("UpdatePersonelSorgu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 0.
        /// </summary>
        public static string Zero {
            get {
                return ResourceManager.GetString("Zero", resourceCulture);
            }
        }
    }
}
