//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Utility {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ResourceMusteri {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ResourceMusteri() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Utility.ResourceMusteri", typeof(ResourceMusteri).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @adParam.
        /// </summary>
        public static string AdParam {
            get {
                return ResourceManager.GetString("AdParam", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DELETE FROM TblSatis WHERE MUSTERI=@p1; DELETE FROM TblMusteri WHERE MUSTERIID=@p1.
        /// </summary>
        public static string DeleteMusteriSorgu {
            get {
                return ResourceManager.GetString("DeleteMusteriSorgu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @p1.
        /// </summary>
        public static string IdParameter {
            get {
                return ResourceManager.GetString("IdParameter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to INSERT INTO TblMusteri(MUSTERIAD,MUSTERISOYAD) VALUES (@p1, @p2).
        /// </summary>
        public static string InsertMusteriSorgu {
            get {
                return ResourceManager.GetString("InsertMusteriSorgu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MUSTERIAD.
        /// </summary>
        public static string MUSTERIAD {
            get {
                return ResourceManager.GetString("MUSTERIAD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Müşteri eklenemedi! Lütfen tüm bilgileri eksiksiz giriniz..
        /// </summary>
        public static string MusteriEkleError {
            get {
                return ResourceManager.GetString("MusteriEkleError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Müşteri güncellenemedi! Lütfen tüm bilgileri eksiksiz giriniz..
        /// </summary>
        public static string MusteriGuncelleError {
            get {
                return ResourceManager.GetString("MusteriGuncelleError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MUSTERIID.
        /// </summary>
        public static string MUSTERIID {
            get {
                return ResourceManager.GetString("MUSTERIID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Musteriler.aspx.
        /// </summary>
        public static string MusterilerSayfasi {
            get {
                return ResourceManager.GetString("MusterilerSayfasi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MUSTERISOYAD.
        /// </summary>
        public static string MUSTERISOYAD {
            get {
                return ResourceManager.GetString("MUSTERISOYAD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @p1.
        /// </summary>
        public static string Parameter1 {
            get {
                return ResourceManager.GetString("Parameter1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @p2.
        /// </summary>
        public static string Parameter2 {
            get {
                return ResourceManager.GetString("Parameter2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT * FROM TblMusteri WHERE MUSTERIID=@p1.
        /// </summary>
        public static string SelectMusteriByIdSorgu {
            get {
                return ResourceManager.GetString("SelectMusteriByIdSorgu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT * FROM TblMusteri.
        /// </summary>
        public static string SelectMusteriSorgu {
            get {
                return ResourceManager.GetString("SelectMusteriSorgu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @soyadParam.
        /// </summary>
        public static string SoyadParam {
            get {
                return ResourceManager.GetString("SoyadParam", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update TblMusteri SET MUSTERIAD=@adParam,MUSTERISOYAD=@soyadParam where MUSTERIID=@p1.
        /// </summary>
        public static string UpdateMusteriSorgu {
            get {
                return ResourceManager.GetString("UpdateMusteriSorgu", resourceCulture);
            }
        }
    }
}
