//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Utility {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ResourceDepartman {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ResourceDepartman() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Utility.ResourceDepartman", typeof(ResourceDepartman).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @p2.
        /// </summary>
        public static string AdParameter {
            get {
                return ResourceManager.GetString("AdParameter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DELETE FROM TblPersonel WHERE PERDEPARTMAN=@p1; DELETE FROM TblDepartman WHERE DEPARTMANID=@p1.
        /// </summary>
        public static string DeleteDepartmanSorgu {
            get {
                return ResourceManager.GetString("DeleteDepartmanSorgu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DEPARTMANAD.
        /// </summary>
        public static string DEPARTMANAD {
            get {
                return ResourceManager.GetString("DEPARTMANAD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Departman eklenemedi! Lütfen tüm bilgileri eksiksiz giriniz..
        /// </summary>
        public static string DepartmanEkleError {
            get {
                return ResourceManager.GetString("DepartmanEkleError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Departman güncellenemedi! Lütfen tüm bilgileri eksiksiz giriniz..
        /// </summary>
        public static string DepartmanGuncelleError {
            get {
                return ResourceManager.GetString("DepartmanGuncelleError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DEPARTMANID.
        /// </summary>
        public static string DEPARTMANID {
            get {
                return ResourceManager.GetString("DEPARTMANID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Departmanlar.aspx.
        /// </summary>
        public static string DepartmanlarSayfasi {
            get {
                return ResourceManager.GetString("DepartmanlarSayfasi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @p1.
        /// </summary>
        public static string IdParameter {
            get {
                return ResourceManager.GetString("IdParameter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to INSERT INTO TblDepartman (DEPARTMANAD) VALUES (@p1).
        /// </summary>
        public static string InsertDepartmanSorgu {
            get {
                return ResourceManager.GetString("InsertDepartmanSorgu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @p1.
        /// </summary>
        public static string Parameter {
            get {
                return ResourceManager.GetString("Parameter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT * FROM TblDepartman WHERE DEPARTMANID=@p1.
        /// </summary>
        public static string SelectDepartmanByIdSorgu {
            get {
                return ResourceManager.GetString("SelectDepartmanByIdSorgu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT * FROM TblDepartman.
        /// </summary>
        public static string SelectDepartmanSorgu {
            get {
                return ResourceManager.GetString("SelectDepartmanSorgu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UPDATE TblDepartman SET DEPARTMANAD=@p2 WHERE DEPARTMANID=@p1.
        /// </summary>
        public static string UpdateDepartmanSorgu {
            get {
                return ResourceManager.GetString("UpdateDepartmanSorgu", resourceCulture);
            }
        }
    }
}
